### ISSUE TITLE
Container force stop

### ISSUE THREAD

**Issue by un4ckn0wl3z** [jogetworkflow/docker-joget#2]
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar,
Buildfile: build.xml,
,,
:,
    [input] skipping input as property db.host has already been set.,
    [input] skipping input as property db.port has already been set.,
    [input] skipping input as property db.name has already been set.,
    [input] skipping input as property db.user has already been set.,
    [input] skipping input as property db.password has already been set.,
    [input] skipping input as property profile.name has already been set.,
,
create-db:,
     [echo] Creating database, please wait...,
     [exec] mysql: [Warning] Using a password on the command line interface can be insecure.,
     [exec] ERROR 1007 (HY000) at line 1: Can't create database 'jwdb'; database exists,
     [exec] Result: 1,
     [exec] mysql: [Warning] Using a password on the command line interface can be insecure.,
,
create-profile:,
     [copy] Copying 1 file to /opt/joget/wflow,
[propertyfile] Creating new property file: /opt/joget/wflow/app_datasource.properties,
,
setup:,
,
BUILD SUCCESSFUL,
Total time: 5 seconds,
2020-07-01 08:47:28.216 INFO  org.glowroot - Glowroot version: 0.13.4, built 2019-04-21 20:27:33 +0000,
2020-07-01 08:47:28.221 INFO  org.glowroot - Java version: 1.8.0_222 (Private Build / Linux),
2020-07-01 08:47:28.222 INFO  org.glowroot - Java args: -Xmx512m -javaagent:/opt/joget/wflow//aspectjweaver-1.8.5.jar -javaagent:/opt/joget/wflow//glowroot/glowroot.jar,
2020-07-01 08:47:35.840 INFO  org.glowroot - creating glowroot schema...,
2020-07-01 08:47:36.703 INFO  org.glowroot - glowroot schema created,
2020-07-01 08:47:37.660 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect),
01-Jul-2020 08:47:38.389 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.41,
01-Jul-2020 08:47:38.398 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 4 2019 09:17:16 UTC,
01-Jul-2020 08:47:38.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.41.0,
01-Jul-2020 08:47:38.399 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux,
01-Jul-2020 08:47:38.400 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-29-generic,
01-Jul-2020 08:47:38.400 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64,
01-Jul-2020 08:47:38.401 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre,
01-Jul-2020 08:47:38.401 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10,
01-Jul-2020 08:47:38.402 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build,
01-Jul-2020 08:47:38.403 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/joget/apache-tomcat-8.5.41,
01-Jul-2020 08:47:38.404 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/joget/apache-tomcat-8.5.41,
01-Jul-2020 08:47:38.405 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/joget/apache-tomcat-8.5.41/conf/logging.properties,
01-Jul-2020 08:47:38.406 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager,
01-Jul-2020 08:47:38.407 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx512m,
01-Jul-2020 08:47:38.408 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dwflow.home=/opt/joget/wflow/,
01-Jul-2020 08:47:38.408 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/opt/joget/wflow//aspectjweaver-1.8.5.jar,
01-Jul-2020 08:47:38.409 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/opt/joget/wflow//glowroot/glowroot.jar,
01-Jul-2020 08:47:38.409 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048,
01-Jul-2020 08:47:38.410 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources,
01-Jul-2020 08:47:38.411 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027,
01-Jul-2020 08:47:38.411 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=,
01-Jul-2020 08:47:38.412 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/joget/apache-tomcat-8.5.41,
01-Jul-2020 08:47:38.412 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/joget/apache-tomcat-8.5.41,
01-Jul-2020 08:47:38.414 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/joget/apache-tomcat-8.5.41/temp,
01-Jul-2020 08:47:38.415 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib],
01-Jul-2020 08:47:38.694 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"],
01-Jul-2020 08:47:38.711 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read,
01-Jul-2020 08:47:38.768 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1534 ms,
01-Jul-2020 08:47:38.836 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina],
01-Jul-2020 08:47:38.837 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.41,
01-Jul-2020 08:47:38.916 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/joget/apache-tomcat-8.5.41/webapps/jw.war],
01-Jul-2020 08:48:07.219 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.,
INFO  01 Jul 2020 08:48:21 org.joget.commons.util.SetupManager  - Using base directory: /opt/joget/wflow/,
INFO  01 Jul 2020 08:48:27 org.joget.commons.util.DynamicDataSource  - profileName=default, url=jdbc:mysql://jwdb:3306/jwdb?characterEncoding=UTF-8, user=joget,
INFO  01 Jul 2020 08:48:30 bitronix.tm.BitronixTransactionManager  - Bitronix Transaction Manager version 2.1.4,
INFO  01 Jul 2020 08:48:30 bitronix.tm.Configuration  - JVM unique ID: <btm-joget>,
INFO  01 Jul 2020 08:48:30 bitronix.tm.recovery.Recoverer  - recovery committed 0 dangling transaction(s) and rolled back 0 aborted transaction(s) on 0 resource(s) [] (restricted to serverId 'btm-joget'),
INFO  01 Jul 2020 08:48:32 org.joget.commons.util.SetupManager  - Initializing setup cache,
INFO  01 Jul 2020 08:48:34 org.joget.plugin.base.PluginManager  - PluginManager initialized,
INFO  01 Jul 2020 08:49:26 org.joget.workflow.model.service.WorkflowManagerImpl  - Datasource bound to jwdb,
SharkEngineManager -> Shark engine is being initialized ...,
Unknown JDBC Driver Vendor for : null using default (Standard) instead,
/opt/joget/run.sh: line 20:    31 Killed                  ./apache-tomcat-8.5.41/bin/catalina.sh run,

**Comment by juljog** [comment]
Hi,

From the message `Killed ./apache-tomcat-8.5.41/bin/catalina.sh run`, it appears that there is insufficient memory available so the Java process was killed by the OS.
