### ISSUE TITLE
Make text area mandatory for some conditions

### ISSUE THREAD

**Issue by charlottemar92** [jogetworkflow/docker-joget#3]
Hi

![mandatory](https://user-images.githubusercontent.com/31487469/101025600-79c46e80-357e-11eb-891a-4fa65c428f8e.jpeg)

considering image above, is it possible to make the last textarea mandatory only if the user checked "Approved"?

Thank you in advance

**Comment by juljog** [comment]
Hi,

If you have questions or discussions like this it's better to post on the community Q&A at https://answers.joget.org, issues here on GitHub should be detailed bug reports.

Thanks!
